#!/usr/bin/env python
# coding: utf-8
import os
import datetime
import pandas as pd

from shared import load_transactions
from transformer import feature_transformation

DIR_INPUT = os.getenv('source_location', './data/audit/')
DIR_OUTPUT = os.getenv('target_location', './data/training/')

# load all audit files and the training files generated by the simulator
files = [os.path.join(DIR_INPUT, f) for f in os.listdir(DIR_INPUT)]
tx_df = load_transactions(files, time_window=30)


# transform transactions, calculate the customer stats and the terminal risk assement
tx_df = feature_transformation(tx_df)

# convert datetime to timestamp
tx_df['TX_DATETIME'] = pd.to_numeric(tx_df['TX_DATETIME']) / 1000000000

# save the new training data
if not os.path.exists(DIR_OUTPUT):
    os.makedirs(DIR_OUTPUT)

ts = int(datetime.datetime.timestamp(datetime.datetime.now()) * 100000)
tx_df.to_csv(DIR_OUTPUT+f"training_{ts}.csv", index=False)
tx_df.to_csv(DIR_OUTPUT+"training_latest.csv", index=False)
