apiVersion: v1
kind: List
items:  
  - kind: ClusterTask
    apiVersion: tekton.dev/v1beta1
    metadata:
      name: run-notebook
    spec:
      params:
        - name: NOTEBOOKS
          type: string
          description: A list of Jupyter Notebooks to run.
        - name: PATH_CONTEXT
          description: The location of the path to run the notebook from.
          default: .
          type: string
        - name: EXTRA_ENV
          type: string
        - name: PAPERMILL_VERSION
          description: The version of Papermill to install.
          default: 2.3.4
        - name: DELETE_VIRTUAL_ENV
          description: Deletes the python virtual environment if set to 'true'.
          default: 'false'
      steps:
        - script: >
            #!/usr/bin/env sh

            set -eu

            if [[ ! -z "$PARAM_EXTRA_ENV" ]] ; then
              echo "exporting EXTRA_ENV"

              IFS=', ' read -r -a array <<< "$PARAM_EXTRA_ENV"

              for element in "${array[@]}"
              do
                  export "$element"
              done
            fi

            cd $(params.PATH_CONTEXT)

            if [[ "$PARAM_DELETE_VIRTUAL_ENV" = 'true' ]] ; then
                rm -rf venv
            fi

            if [[ ! -d "venv" ]] ; then
              python -m venv venv
            fi
            
            source venv/bin/activate

            pip install -r requirements.txt

            pip install papermill==$(params.PAPERMILL_VERSION)

            papermill --log-output $(params.NOTEBOOKS) output.ipynb
          env:
          - name: PARAM_EXTRA_ENV
            value: $(params.EXTRA_ENV)
          - name: PARAM_DELETE_VIRTUAL_ENV
            value: $(params.DELETE_VIRTUAL_ENV)
          image: ubi8/python-39
          name: 'run-notebooks'
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 2
          volumeMounts:
            - mountPath: /gen-source
              name: gen-source
          workingDir: $(workspaces.source.path)
      volumes:
        - emptyDir: {}
          name: gen-source
      workspaces:
        - mountPath: /workspace/source
          name: source

  - kind: ClusterTask
    apiVersion: tekton.dev/v1beta1
    metadata:
      name: inspect
    spec:
      steps:
        - script: >
            #!/usr/bin/env sh

            set -eu

            ls -la /workspace/source
          image: ubi8/ubi-minimal
          name: ''
          resources: {}
          volumeMounts:
            - mountPath: /gen-source
              name: gen-source
          workingDir: $(workspaces.source.path)
      volumes:
        - emptyDir: {}
          name: gen-source
      workspaces:
        - mountPath: /workspace/source
          name: source

  - kind: ClusterTask
    apiVersion: tekton.dev/v1beta1
    metadata:
      name: copy-file
    spec:
      params:
        - name: SRC_PATH
          type: string
          description: The files source path, relative to PATH_CONTEXT
        - name: DEST_PATH
          type: string
          description: The files destination path, relative to PATH_CONTEXT
        - name: PATH_CONTEXT
          description: The location of the path to run the notebook from.
          default: .
        - name: EXTRA_PARAMS
          type: string
          description: Additional params for the cp command.
          default: .
      steps:
        - script: >
            #!/usr/bin/env sh

            set -eu

            if [[ "$PARAM_EXTRA_PARAMS" = '.' ]] ; then
              export PARAM_EXTRA_PARAMS=
            fi

            cd $(params.PATH_CONTEXT)

            cp $PARAM_EXTRA_PARAMS $(params.SRC_PATH) $(params.DEST_PATH)
          env:
          - name: PARAM_EXTRA_PARAMS
            value: $(params.EXTRA_PARAMS)
          image: ubi8/ubi-minimal
          name: ''
          resources: {}
          volumeMounts:
            - mountPath: /gen-source
              name: gen-source
          workingDir: $(workspaces.source.path)
      volumes:
        - emptyDir: {}
          name: gen-source
      workspaces:
        - mountPath: /workspace/source
          name: source